version: '2'

services:
  void-mail:
    build: .
    ports:
      - "3000:3000"
    environment:
      DOMAIN: premium4you.tech
      IMAP_SERVER: us2.imap.mailhostbox.com
      IMAP_USER: sam@premium4you.tech
      IMAP_PASSWORD: q#I(pisCC8
      DELETE_MAILS_OLDER_THAN_DAYS: 30
      
